### PR TITLE
243 sending photos

### PR DESCRIPTION
**Pull request by snasif**
I managed to make photos, videos, files and contact info work both ways.

### CODE REVIEW

**Comment by kyang72** [comment]
Looks good to me. What do you mean by "contact info"?

**Comment by kyang72** [comment]
Looks good to me. I'll wait for Halle's approval too

**Review by hkcountryman — CHANGES_REQUESTED** [review]
What's going on with these? It says you don't have certain attributes in the class. There are also the usual linter errors, those are trivial to fix though.

image

image

image

This is just a warning, but since you don't have the linters I thought I'd bring it to your attention:

image

Then in app.py:

image

That one looks easy to fix but I don't want to assume anything. `Optional` means basically `str | None`. Is that what you wanted instead of `str` inside of `List[str]`?

I made a few changes to the formatting, mainly that you don't have the same settings for autopep8 or you're using a different formatter or something. I notice you often make changes where linebreaks have been deleted. Are your settings like this?

```json
{
    "[python]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": true,
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.autopep8",
    },
    "autopep8.args": ["-a", "-a"],
    "autopep8.importStrategy": "fromEnvironment",
    "python.formatting.provider": "none",
    "python.languageServer": "Pylance",
    "python.linting.mypyEnabled": true,
    "python.linting.mypyArgs": ["--show-error-codes", "--check-untyped-defs"],
    "python.linting.pylintEnabled": true,
    "python.linting.pylintArgs": ["--rcfile=${workspaceFolder}/.pylintrc"],
    "autoDocstring.docstringFormat": "pep257",
    "autoDocstring.generateDocstringOnEnter": true,
}
```

**Comment by hkcountryman** [comment]
By the way, most of the line too long errors are fixed when you get the right autopep8 settings

**Review by snasif — COMMENTED** [review]
The requested changes have been fixed.

**Review by hkcountryman — APPROVED** [review]

**Pull request merged**
